#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using YouthConference.Models;

namespace YouthConference.Models	
{
	public partial class YouthConferenceModels : OpenAccessContext, IYouthConferenceModelsUnitOfWork
	{
		private static string connectionStringName = @"DefaultConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = new YouthConferenceModelsFluentMetadataSource();
		
		public YouthConferenceModels()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public YouthConferenceModels(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public YouthConferenceModels(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public YouthConferenceModels(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public YouthConferenceModels(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<UserProfile> UserProfiles 
		{
			get
			{
				return this.GetAll<UserProfile>();
			}
		}
		
		public IQueryable<Registrant> Registrants 
		{
			get
			{
				return this.GetAll<Registrant>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "mssql";
			backend.ProviderName = "System.Data.SqlClient";
			backend.Logging.MetricStoreSnapshotInterval = 0;
			backend.SecondLevelCache.Enabled = true;
			backend.SecondLevelCache.CacheQueryResults = true;
			backend.SecondLevelCache.NumberOfQueryResults = 20000;
			backend.ConnectionPool.Pool = ConnectionPoolType.ADOManaged;
			backend.ConnectionPool.MaxActive = 50;
			backend.Runtime.ClassBehavior = DataAccessKind.ReadWrite;
			backend.Runtime.CacheReferenceType = CacheReferenceType.Weak;
			backend.Runtime.ReturnNullForRowNotFound = true;
			backend.Runtime.CompiledQueryCacheSize = 2000;
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of YouthConferenceModels.
		/// </summary>
		/// <param name="config">The BackendConfiguration of YouthConferenceModels.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IYouthConferenceModelsUnitOfWork : IUnitOfWork
	{
		IQueryable<UserProfile> UserProfiles
		{
			get;
		}
		IQueryable<Registrant> Registrants
		{
			get;
		}
	}
}
#pragma warning restore 1591
