#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the FluentMappingGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using YouthConference.Models;
using Telerik.OpenAccess.Metadata.Relational;

namespace YouthConference.Models
{

	public partial class YouthConferenceModelsFluentMetadataSource : FluentMetadataSource
	{
		
		protected override IList<MappingConfiguration> PrepareMapping()
		{
			List<MappingConfiguration> mappingConfigurations = new List<MappingConfiguration>();
			
			MappingConfiguration<UserProfile> userprofileConfiguration = this.GetUserProfileMappingConfiguration();
			mappingConfigurations.Add(userprofileConfiguration);
			
			MappingConfiguration<Registrant> registrantConfiguration = this.GetRegistrantMappingConfiguration();
			mappingConfigurations.Add(registrantConfiguration);
			
			return mappingConfigurations;
		}
		
		protected override void SetContainerSettings(MetadataContainer container)
		{
			container.Name = "YouthConferenceModels";
			container.DefaultNamespace = "YouthConference.Models";
			container.NameGenerator.RemoveLeadingUnderscores = false;
			container.NameGenerator.SourceStrategy = Telerik.OpenAccess.Metadata.NamingSourceStrategy.Property;
			container.NameGenerator.RemoveCamelCase = false;
		}
		public MappingConfiguration<UserProfile> GetUserProfileMappingConfiguration()
		{
			MappingConfiguration<UserProfile> configuration = this.GetUserProfileClassConfiguration();
			this.PrepareUserProfilePropertyConfigurations(configuration);

			return configuration;
		}

		public MappingConfiguration<UserProfile> GetUserProfileClassConfiguration()
		{
			MappingConfiguration<UserProfile> configuration = new MappingConfiguration<UserProfile>();
			configuration.MapType(x => new { });
	
			return configuration;
		}
	
		public void PrepareUserProfilePropertyConfigurations(MappingConfiguration<UserProfile> configuration)
		{
			configuration.HasProperty(x => x.UserId).IsIdentity().HasFieldName("_userId");
			configuration.HasProperty(x => x.UserName).HasFieldName("_userName");
		}
		public MappingConfiguration<Registrant> GetRegistrantMappingConfiguration()
		{
			MappingConfiguration<Registrant> configuration = this.GetRegistrantClassConfiguration();
			this.PrepareRegistrantPropertyConfigurations(configuration);

			return configuration;
		}

		public MappingConfiguration<Registrant> GetRegistrantClassConfiguration()
		{
			MappingConfiguration<Registrant> configuration = new MappingConfiguration<Registrant>();
			configuration.MapType(x => new { }).WithCascadeDelete(CascadeDeleteOption.No);
	
			return configuration;
		}
	
		public void PrepareRegistrantPropertyConfigurations(MappingConfiguration<Registrant> configuration)
		{
			configuration.HasProperty(x => x.Id).IsIdentity(KeyGenerator.Autoinc).HasFieldName("_id");
			configuration.HasProperty(x => x.FirstName).HasFieldName("_firstName");
			configuration.HasProperty(x => x.MiddleName).HasFieldName("_middleName");
			configuration.HasProperty(x => x.LastName).HasFieldName("_lastName");
			configuration.HasProperty(x => x.State).HasFieldName("_state");
			configuration.HasProperty(x => x.Email).HasFieldName("_email");
			configuration.HasProperty(x => x.PhoneNumber).HasFieldName("_phoneNumber");
			configuration.HasProperty(x => x.Gender).HasFieldName("_gender");
			configuration.HasProperty(x => x.Institution).HasFieldName("_institution");
		}
	}
}
#pragma warning restore 1591
